### ISSUE TITLE
Not a map file. Node 'Map' not found.

### ISSUE THREAD

**Issue by sprguillen** [mapnik/node-mapnik-sample-code#4]
I tried to open a .osm file written in xml with the following code:

    map.load('./export.osm', function (err, map) {
        if (err) throw err;

        map.zoomAll();
        var im = new mapnik.Image(256, 256);
        map.render(im, function (err, im) {
            if (err) throw err;

            im.encode('png', function (err, buffer) {
                if (err) throw err;
                fs.writeFile('map.png', buffer, function (err) {
                    if (err) throw err;
                    console.log('saved map image to map.png');
                });
            })
        });
    });

But i got an error <b>Not a map file. Node 'Map' not found.</b>

There's an instruction found here: https://github.com/mapnik/mapnik/wiki/InstallationTroubleshooting but the solution wasn't clear enough for me. How can I rebuild mapnik? It also gave a sample code that I should run:

    python scons/scons.py install XMLPARSER=libxml2

How can I solve this problem? I'm running node-mapnik on windows. Since I didn't build this using Ubuntu and I didn't <b>make install</b> this. Instead I used <b>npm install mapnik@latest</b>. I also have mapnik configured on my system path. Please help me.

PS: I can't post the contents inside export.osm because openstreetmaps doesn't allow me to.

**Comment by MilanVilov** [comment]
Hi there, i came upon same problem. Any advice how you solved it ?

**Comment by sprguillen** [comment]
Sorry, this was a long time ago. I only saw your post now since I'm inactive in Github, I'm afraid I forgot the solution to the problem. I was too busy to post the answer here when I got it. My apologies.
